packages:
  - packages/*
  - apps/*
  - plugins/*

catalog:
  '@types/node': ^26.0.1
  '@types/three': ^0.185.0
  '@vitejs/plugin-vue': ^6.0.7
  '@vue/language-core': ^3.3.5
  element-plus: ^2.14.2
  three: ^0.170.0
  typescript: ^6.0.3
  vite: ^8.1.0
  vite-plugin-dts: ^5.0.3
  vue: ^3.5.39
  vue-tsc: ^3.3.5
